# Generated by Django 4.0.3 on 2022-04-18 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('correo', models.CharField(max_length=128)),
                ('contraseña', models.CharField(max_length=64)),
                ('tipo', models.CharField(choices=[('Negocio', 'Negocio'), ('Particular', 'Particular')], max_length=64)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
