# Generated by Django 4.0.4 on 2022-05-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recogida_entrega', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=128)),
                ('modelo', models.CharField(max_length=128)),
                ('gama', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=64)),
                ('estado', models.CharField(choices=[('Libre', 'Libre'), ('Reservado', 'Reservado'), ('No disponible', 'No Disponible')], max_length=64)),
                ('url', models.CharField(default='', max_length=128)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recogida_entrega.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=128)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coches_disponibles.coches')),
            ],
        ),
    ]
