# Generated by Django 4.0.4 on 2022-05-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Por día y por kilometraje', 'Dia Km'), ('Por día y kilometraje ilimitado', 'Dia Km Ilim'), ('Por fin de semana', 'Fin Semana'), ('Por semana', 'Semanal'), ('Larga duración', 'Larga Duracion')], default='No Disponible', max_length=64)),
                ('gama', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='No Disponible', max_length=64)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
