# Generated by Django 4.0.3 on 2022-04-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recogida_entrega', '0001_initial'),
        ('coches_disponibles', '0001_initial'),
        ('account', '0001_initial'),
        ('tarifas_disponibles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_rec', models.DateField()),
                ('fecha_dev', models.DateField()),
                ('hora_rec', models.TimeField()),
                ('hora_dev', models.TimeField()),
                ('tarjeta_credito', models.IntegerField()),
                ('id_coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coches_disponibles.coches')),
                ('id_extra', models.ManyToManyField(to='modificar_reserva.extras')),
                ('id_oficina_dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugar_devolucion', to='recogida_entrega.oficina')),
                ('id_oficina_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugar_recogida', to='recogida_entrega.oficina')),
                ('id_opciones', models.ManyToManyField(to='coches_disponibles.opciones')),
                ('id_tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifas_disponibles.tarifas')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usuario')),
            ],
        ),
    ]
