# Generated by Django 4.0.4 on 2022-05-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recogida_entrega', '0001_initial'),
        ('tarifas_disponibles', '0001_initial'),
        ('coches_disponibles', '0002_alter_opciones_opcion'),
        ('account', '0001_initial'),
        ('modificar_reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='descuento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modificar_reserva.descuentos'),
        ),
        migrations.AlterField(
            model_name='descuentos',
            name='porcentaje',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='extras',
            name='extra',
            field=models.CharField(choices=[('Wi-Fi', 'Wifi'), ('GPS', 'Gps'), ('Silla para niños', 'Silla'), ('Cadenas de nieve', 'Cadenas')], max_length=256),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='coche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coches_disponibles.coches'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_dev',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_rec',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_dev',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_rec',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='oficina_dev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugar_devolucion', to='recogida_entrega.oficina'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='oficina_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugar_recogida', to='recogida_entrega.oficina'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas_disponibles.tarifas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.usuario'),
        ),
    ]
